#!/usr/bin/env bash
# installs nginx on web-01 server
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School for the win!" > /var/www/html/index.html
service nginx start