#!/usr/bin/env bash
# redirection
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://twitter.com permanent;" /etc/nginx/sites-available/default
service nginx start
