#!/usr/bin/env bash
# redirection
apt-get update
apt-get -y install nginx
echo "Holberton School for the win!" > /var/www/html/index.html
sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://twitter.com permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i "/listen 80 default_server/a error_page 404 /custom_404.html; location = /custom_404.html { root /usr/share/nginx/html; internal; }" /etc/nginx/sites-available/default
service nginx start