#!/usr/bin/env bash
# Install nginx web server & name header
apt-get update
apt-get install nginx
ufw allow 'Nginx HTTP'
header="add_header X-Served-By $HOSTNAME;"
sed -i "20i $header" /etc/nginx/sites-available/default
service nginx restart

