#!/usr/bin/env bash
#Install nginx web server & name header
apt-get -y update
apt-get -y install nginx
header="add_header X-Served-By $HOSTNAME;"
sed -i "20i $header" /etc/nginx/sites-available/default
service nginx restart

