#!/usr/bin/env bash
#Bash script that loops
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Holberton School for the other iterations
x=1
while [ $x -lt 11 ]
do
	if [ $x -eq 4 ]
	then
	echo "bad luck"
	elif [ $x -eq 8 ]
	then
	echo "good luck"
	else
	echo "Holberton School"
	fi
	(( x++ ))
done
