#!/usr/bin/env bash
# displays numbers from 1 to 20
# displays '4' and then "bad luck from China" for the 4th iteration
# displays '9' and then "bad luck from Japan for the 9th iteration
# displays "17" and then "bad luck from Italy" for the 17th iteration
x=1
while [ $x -le 20 ]
do
	echo $x
	case $x in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"	
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	(( x++ ))
done
